### ISSUE TITLE
RFE: dfuzzer should probably send corrupted DBus messages

### ISSUE THREAD

**Issue by evverx** [dbus-fuzzer/dfuzzer#102]
It's probably a niche feature (and it isn't clear whether it's in scope) but it can help to uncover bugs like https://github.com/bus1/dbus-broker/issues/291.

**Comment by mrc0mmand** [comment]
I'd say it's definitely in the scope. The main issue is going to be to convince gdbus to send malformed messages :-)

Do you have some examples of such messages at hand?

**Comment by evverx** [comment]
> Do you have some examples of such messages at hand?

There are 4 messages crashing dbus-broker in one of my private repositories. I think you should have access to it.

>  The main issue is going to be convincing gdbus to send malformed messages :-)

I'm not sure it's possible :-) I think the idea is not to send malformed messages using the library.

**Comment by evverx** [comment]
On second thought though in terms of catching bugs like that I think ideally `dbus-broker` itself should be fuzzed. It would be much more effective than sending weird stuff via its socket and waiting for it to crash. I'm pretty sure it would be accepted to OSS-Fuzz because it can be considered a critical open-source projects given that it's used by default in large distributions.

**Comment by mrc0mmand** [comment]
> On second thought though in terms of catching bugs like that I think ideally `dbus-broker` itself should be fuzzed. It would be much more effective than sending weird stuff via its socket and waiting for it to crash. I'm pretty sure it would be accepted to OSS-Fuzz because it can be considered a critical open-source project given that it's used by default in large distributions.

Agreed, that sounds like the most effective way. I mean, sending malformed messages should be possible (albeit not directly with gdbus APIs), but without instrumentation and coverage data it would be far less efficient.

**Comment by evverx** [comment]
-> https://github.com/google/oss-fuzz/pull/7860
