### ISSUE TITLE
Send dfuzzer to coverity automatically

### ISSUE THREAD

**Issue by evverx** [dbus-fuzzer/dfuzzer#31]
I have a script that can do that but for it to work on GitHub a secret named `COVERITY_SCAN_TOKEN` should be added to the repository: https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository. It should be set to the project token on Coverity (which can be found at https://scan.coverity.com/projects/dfuzzer?tab=project_settings).

**Comment by evverx** [comment]
@matusmarhefka I invited you to the dfuzzer project on Coverity so in theory you should have access to that token.

**Comment by matusmarhefka** [comment]
> I have a script that can do that but for it to work on GitHub a secret named `COVERITY_SCAN_TOKEN` should be added to the repository: https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository. It should be set to the project token on Coverity (which can be found at https://scan.coverity.com/projects/dfuzzer?tab=project_settings).

For some reason I cannot sign-in into Coverity using GH account, I've authorized Coverity in my GH, but when I try to sign-in I am getting `Please confirm your account to continue.`, but I don't see any confirmation email :(

**Comment by evverx** [comment]
@matusmarhefka I think I specified the Red Hat email address I found in the commit messages there. Could it be that your github account is linked to a different email address?

**Comment by matusmarhefka** [comment]
> @matusmarhefka I think I specified the Red Hat email address I found in the commit messages there. Could it be that your github account is linked to a different email address?

Nope, I am using RH email as primary.

**Comment by evverx** [comment]
@matusmarhefka I've just sent three emails on behalf of Coverity Scan. If you haven't received them I suspect there is a filter of some kind at RH rejecting those emails. @mrc0mmand I wonder if you have ever tried to make it work with your RH email address?

**Comment by mrc0mmand** [comment]
Interesting, it really seems RH is filtering out emails from Coverity, since I haven't received the email either when I sent it to my RH address. Maybe @kdudka (our internal Coverity guru/point-of-contact) could help here?

**Comment by evverx** [comment]
My guess would be that it has something to do with the fact that commercial Synopsys products (including Coverity) are used at RH internally, which I assume prevents RH employees from using free services like Coverity Scan on behalf of RH at least so either RH rejects those emails or Synopsys don't send them in the first place. I might be wrong of course.

**Comment by kdudka** [comment]
Not really.  The Coverity license that we use at Red Hat internally is completely isolated from scan.coverity.com.  Moreover, we do not use Github or e-mail address-based authentication on our internal instance of Coverity.  Each instance also uses its own support channels.

**Comment by mrc0mmand** [comment]
@matusmarhefka would migrating this repo under a separate organization (like dfuzzer) would be okay with you? That way we could manage all the CIs (and their respective shared secrets) without bothering you. If so, you could create the organization, move the repo there and add me and @evverx there? Thank you!

**Comment by matusmarhefka** [comment]
@mrc0mmand Transferred, dfuzzer name was taken so organization name is dbus-fuzzer

**Comment by evverx** [comment]
@matusmarhefka thanks! As far as I can see @mrc0mmand and I are members but only owners have access to those settings. Could you make @mrc0mmand an owner? I think it should be enough to add that token.

**Comment by matusmarhefka** [comment]
@evverx Updated, @mrc0mmand is now an owner.

**Comment by mrc0mmand** [comment]
Excellent, thanks a lot, @matusmarhefka!

@evverx I've added the Coverity token as `COVERITY_SCAN_TOKEN` to the repo secrets, so now it should be possible to add an action which sends the builds to Coverity automagically.

**Comment by evverx** [comment]
Done in https://github.com/dbus-fuzzer/dfuzzer/pull/94
