### ISSUE TITLE
`dfuzzer -l` isn't machine-friendly

### ISSUE THREAD

**Issue by evverx** [dbus-fuzzer/dfuzzer#67]
This is mostly inspired by https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/14669 where the output of `dfuzzer -l` is parsed with
```perl
my $output = script_output('./dfuzzer -l 2>&1');
Amrysliu marked this conversation as resolved.

    # Parse the output and push the items to related array
    my @bus_list;
    foreach my $line (split(/\n/, $output)) {
        $line = trim($line);
        if ($line =~ /SESSION\s+BUS|SYSTEM\s+BUS|Session bus not found/) {
            next;
        }
        elsif ($line =~ /Exit status:\s+(\d)/) {
            if ($1 != 0) {
                record_info('Fail to get system bus information', $output, result => 'fail');
                $self->result('fail');
            }
        } else {
            push(@bus_list, $line);
        }
    }

    record_info('Result of dfuzzer -l', Dumper(\@bus_list));
```
As far as I understand `bus_list` is then used to iterate over DBus services.

**Comment by mrc0mmand** [comment]
Maybe we could make `-l/--list` take an optional argument, let's say `--list=plain`, to show only the respective dbus services (and the session/system bus header). Possibly extending it in the future of `--list=json`, if the need arises?

**Comment by evverx** [comment]
I haven't heard back from the OpenSUSE folks so I think it's safe to assume that they either got it around somehow or hasn't updated dfuzzer yet. Given that this issue was prompted by that particular use case only I think this issue can be closed.
